// Generated by CoffeeScript 1.6.3
var AMDLoader, AbstractMethodError, BasicLoader, CJSLoader, ChangesInWindowError, Loader, PollutionLoader, UndeclaredRequireError, XHR, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

AbstractMethodError = (function(_super) {
  __extends(AbstractMethodError, _super);

  function AbstractMethodError() {
    this.name = this.constructor.name;
    this.message = "Calling abstract method detected.";
  }

  return AbstractMethodError;

})(Error);

UndeclaredRequireError = (function(_super) {
  __extends(UndeclaredRequireError, _super);

  function UndeclaredRequireError(self_name, require_name) {
    this.self_name = self_name;
    this.require_name = require_name;
    this.name = this.constructor.name;
    this.message = "Found unreserved attempt to require of `" + this.require_name + "` inside `" + this.self_name + "`";
  }

  return UndeclaredRequireError;

})(Error);

ChangesInWindowError = (function(_super) {
  __extends(ChangesInWindowError, _super);

  function ChangesInWindowError(self_name, props) {
    this.self_name = self_name;
    this.props = props;
    this.name = this.constructor.name;
    this.message = "During `" + this.self_name + "` loading window object was polluted with: " + props;
  }

  return ChangesInWindowError;

})(Error);

XHR = function() {
  try {
    return new XMLHttpRequest();
  } catch (_error) {

  }
  try {
    return new ActiveXObject("Msxml3.XMLHTTP");
  } catch (_error) {

  }
  try {
    return new ActiveXObject("Msxml2.XMLHTTP.6.0");
  } catch (_error) {

  }
  try {
    return new ActiveXObject("Msxml2.XMLHTTP.3.0");
  } catch (_error) {

  }
  try {
    return new ActiveXObject("Msxml2.XMLHTTP");
  } catch (_error) {

  }
  try {
    return new ActiveXObject("Microsoft.XMLHTTP");
  } catch (_error) {

  }
  return null;
};

BasicLoader = (function() {
  function BasicLoader(options) {
    this.id = options.id;
    this.source = options.source;
    this.deps = options.dependencies;
    this["this"] = {};
    this.window = this.get_window();
    this.errors = [];
  }

  BasicLoader.prototype.render = function() {
    throw new AbstractMethodError();
  };

  BasicLoader.prototype.load = function() {
    var error, func, result;
    func = new Function(this.render());
    try {
      result = func.call(this);
    } catch (_error) {
      error = _error;
      console.log(error);
    }
    try {
      this._check(result);
    } catch (_error) {
      error = _error;
      console.log(error);
    }
    if (this.errors.length > 0) {
      return null;
    }
    return this._make();
  };

  BasicLoader.prototype.get_window = function() {
    return {
      __proto__: window
    };
  };

  BasicLoader.prototype.get_require = function() {
    throw new AbstractMethodError();
  };

  BasicLoader.prototype._fail = function(reason) {
    this.errors.push(reason);
    throw reason;
  };

  BasicLoader.prototype._check = function(result) {
    throw new AbstractMethodError();
  };

  BasicLoader.prototype._make = function() {
    throw new AbstractMethodError();
  };

  return BasicLoader;

})();

CJSLoader = (function(_super) {
  __extends(CJSLoader, _super);

  function CJSLoader(options) {
    CJSLoader.__super__.constructor.call(this, options);
    this.module = {};
    this.exports = {};
    this.module.exports = this.exports;
    this.require = this.get_require();
  }

  CJSLoader.prototype.render = function() {
    return "return (function(module, exports, require, window) { \n    " + this.source + "; \n}).call(this.this, this.module, this.exports, this.require, this.window);";
  };

  CJSLoader.prototype.get_require = function() {
    var require;
    require = function(name) {
      var value;
      value = this.deps[name];
      if (value == null) {
        this._fail(new UndeclaredRequireError(this.id, name));
      }
      return value;
    };
    return require.bind(this);
  };

  CJSLoader.prototype._check = function(result) {};

  CJSLoader.prototype._make = function() {
    return this.module.exports;
  };

  return CJSLoader;

})(BasicLoader);

AMDLoader = (function(_super) {
  __extends(AMDLoader, _super);

  function AMDLoader(options) {
    AMDLoader.__super__.constructor.call(this, options);
    this.define = this.get_define();
  }

  AMDLoader.prototype.render = function() {
    return "return (function(define, window) { \n    " + this.source + "; \n}).call(this.this, this.define, this.window);";
  };

  AMDLoader.prototype.get_define = function() {
    var define;
    define = function(names, func) {
      var deps, name;
      deps = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = names.length; _i < _len; _i++) {
          name = names[_i];
          _results.push(this.deps[name]);
        }
        return _results;
      }).call(this);
      return this.result = func.apply(this["this"], deps);
    };
    return define.bind(this);
  };

  AMDLoader.prototype._check = function(result) {};

  AMDLoader.prototype._make = function() {
    return this.result;
  };

  return AMDLoader;

})(BasicLoader);

PollutionLoader = (function(_super) {
  __extends(PollutionLoader, _super);

  function PollutionLoader() {
    _ref = PollutionLoader.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  PollutionLoader.prototype.render = function() {
    var args, name, names;
    names = ["window"].concat((function() {
      var _results;
      _results = [];
      for (name in this.deps) {
        _results.push(name);
      }
      return _results;
    }).call(this)).join(", ");
    args = ["this.this", "this.window"].concat((function() {
      var _results;
      _results = [];
      for (name in this.deps) {
        _results.push("this.deps[\"" + name + "\"]");
      }
      return _results;
    }).call(this)).join(", ");
    return "return (function(" + names + ") {\n    " + this.source + ";\n}).call(" + args + ");";
  };

  PollutionLoader.prototype._check = function(result) {};

  PollutionLoader.prototype.get_window = function() {
    var name, result, value, _ref1;
    result = {
      __proto__: PollutionLoader.__super__.get_window.call(this)
    };
    _ref1 = this.deps;
    for (name in _ref1) {
      value = _ref1[name];
      result[name] = value;
    }
    return {
      __proto__: result
    };
  };

  PollutionLoader.prototype._make = function() {
    var name, result, value, _ref1, _ref2;
    result = {};
    _ref1 = this.window;
    for (name in _ref1) {
      if (!__hasProp.call(_ref1, name)) continue;
      value = _ref1[name];
      result[name] = value;
    }
    _ref2 = this["this"];
    for (name in _ref2) {
      if (!__hasProp.call(_ref2, name)) continue;
      value = _ref2[name];
      result[name] = value;
    }
    return result;
  };

  return PollutionLoader;

})(BasicLoader);

Loader = (function() {
  function Loader(options) {}

  return Loader;

})();

window.onload = function() {
  var env, module;
  env = new CJSLoader({
    name: "user-code-cjs",
    source: document.getElementById("user-code-cjs").text,
    dependencies: {
      test: console
    }
  });
  env.load();
  module = env.load();
  module.greetings();
  env = new AMDLoader({
    name: "user-code-amd",
    source: document.getElementById("user-code-amd").text,
    dependencies: {
      test: console
    }
  });
  module = env.load();
  module.greetings();
  env = new PollutionLoader({
    name: "user-code-pollution",
    source: document.getElementById("user-code-pollution").text,
    dependencies: {
      test: console
    }
  });
  module = env.load();
  return module.greetings();
};
