// Generated by CoffeeScript 1.7.1
var AMDEvaluator, AMDReturnsNothingError, AbstractMethodError, BasicEvaluator, CJSEvaluator, ChangesInWindowError, ExportsViolationError, Loader, NoSourceError, PollutionEvaluator, ReturnPollutionError, Storage, ThisPollutionError, UndeclaredRequireError, XHR,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __slice = [].slice;

AbstractMethodError = (function(_super) {
  __extends(AbstractMethodError, _super);

  function AbstractMethodError() {
    this.name = "AbstractMethodError";
    this.message = "Calling abstract method detected.";
  }

  return AbstractMethodError;

})(Error);

UndeclaredRequireError = (function(_super) {
  __extends(UndeclaredRequireError, _super);

  function UndeclaredRequireError(self_name, require_name) {
    this.self_name = self_name;
    this.require_name = require_name;
    this.name = "UndeclaredRequireError";
    this.message = "Found unreserved attempt to require of `" + this.require_name + "` inside `" + this.self_name + "`";
  }

  return UndeclaredRequireError;

})(Error);

ChangesInWindowError = (function(_super) {
  __extends(ChangesInWindowError, _super);

  function ChangesInWindowError(self_name, props) {
    this.self_name = self_name;
    this.props = props;
    this.name = "ChangesInWindowError";
    this.message = "During `" + this.self_name + "` loading window object was polluted with: " + props;
  }

  return ChangesInWindowError;

})(Error);

NoSourceError = (function(_super) {
  __extends(NoSourceError, _super);

  function NoSourceError(module_md5, module_url) {
    this.module_md5 = module_md5;
    this.module_url = module_url;
    this.name = "NoSourceError";
    this.message = "Module source with checksum of `" + this.module_md5 + "` was not found in localStorage. Probably it was not loaded from " + module_url + ".";
  }

  return NoSourceError;

})(Error);

ExportsViolationError = (function(_super) {
  __extends(ExportsViolationError, _super);

  function ExportsViolationError(self_name) {
    this.self_name = self_name;
    this.name = "ExportsViolationError";
    this.message = "";
  }

  return ExportsViolationError;

})(Error);

ReturnPollutionError = (function(_super) {
  __extends(ReturnPollutionError, _super);

  function ReturnPollutionError(self_name, props) {
    this.self_name = self_name;
    this.props = props;
    this.name = "ReturnPollutionError";
    this.message = "";
  }

  return ReturnPollutionError;

})(Error);

ThisPollutionError = (function(_super) {
  __extends(ThisPollutionError, _super);

  function ThisPollutionError(self_name, props) {
    this.self_name = self_name;
    this.props = props;
    this.name = "ThisPollutionError";
    this.message = "";
  }

  return ThisPollutionError;

})(Error);

AMDReturnsNothingError = (function(_super) {
  __extends(AMDReturnsNothingError, _super);

  function AMDReturnsNothingError(self_name) {
    this.self_name = self_name;
    this.name = "AMDReturnsNothingError";
    this.message = "";
  }

  return AMDReturnsNothingError;

})(Error);

XHR = function() {
  try {
    return new XMLHttpRequest();
  } catch (_error) {

  }
  try {
    return new ActiveXObject("Msxml3.XMLHTTP");
  } catch (_error) {

  }
  try {
    return new ActiveXObject("Msxml2.XMLHTTP.6.0");
  } catch (_error) {

  }
  try {
    return new ActiveXObject("Msxml2.XMLHTTP.3.0");
  } catch (_error) {

  }
  try {
    return new ActiveXObject("Msxml2.XMLHTTP");
  } catch (_error) {

  }
  try {
    return new ActiveXObject("Microsoft.XMLHTTP");
  } catch (_error) {

  }
  return null;
};

BasicEvaluator = (function() {
  function BasicEvaluator(options) {
    this.id = options.id;
    this.source = options.source;
    this.deps = options.dependencies;
    this["this"] = {};
    this.window = this.get_window();
    this.errors = [];
  }

  BasicEvaluator.prototype.render = function() {
    throw new AbstractMethodError();
  };

  BasicEvaluator.prototype.run = function() {
    var func, result;
    func = new Function(this.render());
    result = func.call(this);
    this._check(result);
    if (this.errors.length > 0) {
      return null;
    }
    return this._make();
  };

  BasicEvaluator.prototype.get_window = function() {
    return {
      __proto__: window
    };
  };

  BasicEvaluator.prototype.get_require = function() {
    throw new AbstractMethodError();
  };

  BasicEvaluator.prototype._fail = function(reason) {
    this.errors.push(reason);
    throw reason;
  };

  BasicEvaluator.prototype._check = function(result) {
    throw new AbstractMethodError();
  };

  BasicEvaluator.prototype._make = function() {
    throw new AbstractMethodError();
  };

  return BasicEvaluator;

})();

CJSEvaluator = (function(_super) {
  __extends(CJSEvaluator, _super);

  function CJSEvaluator(options) {
    CJSEvaluator.__super__.constructor.call(this, options);
    this.module = {};
    this.exports = {};
    this.module.exports = this.exports;
    this.require = this.get_require();
  }

  CJSEvaluator.prototype.render = function() {
    return "return (function(module, exports, require, window) { \n    " + this.source + "; \n}).call(this.this, this.module, this.exports, this.require, this.window);";
  };

  CJSEvaluator.prototype.get_require = function() {
    var require;
    require = function(name) {
      var value;
      value = this.deps[name];
      if (value == null) {
        this._fail(new UndeclaredRequireError(this.id, name));
      }
      return value;
    };
    return require.bind(this);
  };

  CJSEvaluator.prototype._check = function(result) {
    var this_keys, window_keys;
    window_keys = Object.keys(this.window);
    if (window_keys.length !== 0) {
      throw new ChangesInWindowError(this.id, window_keys);
    }
    if (!(this.exports === this.module.exports || Object.keys(this.exports).length === 0)) {
      throw new ExportsViolationError(this.id);
    }
    if (result != null) {
      throw new ReturnPollutionError(this.id, Object.keys(result));
    }
    this_keys = Object.keys(this["this"]);
    if (this_keys.length !== 0) {
      throw new ThisPollutionError(this.id, this_keys);
    }
  };

  CJSEvaluator.prototype._make = function() {
    return this.module.exports;
  };

  return CJSEvaluator;

})(BasicEvaluator);

AMDEvaluator = (function(_super) {
  __extends(AMDEvaluator, _super);

  function AMDEvaluator(options) {
    AMDEvaluator.__super__.constructor.call(this, options);
    this.define = this.get_define();
  }

  AMDEvaluator.prototype.render = function() {
    return "return (function(define, window) { \n    " + this.source + "; \n}).call(this.this, this.define, this.window);";
  };

  AMDEvaluator.prototype.get_define = function() {
    var define;
    define = function(names, func) {
      var deps, name;
      deps = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = names.length; _i < _len; _i++) {
          name = names[_i];
          _results.push(this.deps[name]);
        }
        return _results;
      }).call(this);
      return this.result = func.apply(this["this"], deps);
    };
    return define.bind(this);
  };

  AMDEvaluator.prototype._check = function(result) {
    var this_keys, window_keys;
    window_keys = Object.keys(this.window);
    if (window_keys.length !== 0) {
      throw new ChangesInWindowError(this.id, window_keys);
    }
    if (result != null) {
      throw new ReturnPollutionError(this.id, Object.keys(result));
    }
    this_keys = Object.keys(this["this"]);
    if (this_keys.length !== 0) {
      throw new ThisPollutionError(this.id, this_keys);
    }
    if (this.result == null) {
      throw new AMDReturnsNothingError(this.id);
    }
  };

  AMDEvaluator.prototype._make = function() {
    return this.result;
  };

  return AMDEvaluator;

})(BasicEvaluator);

PollutionEvaluator = (function(_super) {
  __extends(PollutionEvaluator, _super);

  function PollutionEvaluator() {
    return PollutionEvaluator.__super__.constructor.apply(this, arguments);
  }

  PollutionEvaluator.prototype.render = function() {
    var args, name, names;
    names = ["window"].concat((function() {
      var _results;
      _results = [];
      for (name in this.deps) {
        _results.push(name);
      }
      return _results;
    }).call(this)).join(", ");
    args = ["this.this", "this.window"].concat((function() {
      var _results;
      _results = [];
      for (name in this.deps) {
        _results.push("this.deps[\"" + name + "\"]");
      }
      return _results;
    }).call(this)).join(", ");
    return "return (function(" + names + ") {\n    " + this.source + ";\n}).call(" + args + ");";
  };

  PollutionEvaluator.prototype._check = function(result) {
    if (result != null) {
      throw new ReturnPollutionError(this.id, Object.keys(result));
    }
  };

  PollutionEvaluator.prototype.get_window = function() {
    var name, result, value, _ref;
    result = {
      __proto__: PollutionEvaluator.__super__.get_window.call(this)
    };
    _ref = this.deps;
    for (name in _ref) {
      value = _ref[name];
      result[name] = value;
    }
    return {
      __proto__: result
    };
  };

  PollutionEvaluator.prototype._make = function() {
    var name, result, value, _ref, _ref1;
    result = {};
    _ref = this.window;
    for (name in _ref) {
      if (!__hasProp.call(_ref, name)) continue;
      value = _ref[name];
      result[name] = value;
    }
    _ref1 = this["this"];
    for (name in _ref1) {
      if (!__hasProp.call(_ref1, name)) continue;
      value = _ref1[name];
      result[name] = value;
    }
    return result;
  };

  return PollutionEvaluator;

})(BasicEvaluator);

Storage = (function() {
  function Storage() {}

  Storage.prototype.get = function(name) {
    throw new AbstractMethodError();
  };

  Storage.prototype.set = function(name, value) {
    throw new AbstractMethodError();
  };

  return Storage;

})();

Loader = (function() {
  function Loader(options) {
    this._all_modules = {};
    this._modules_running = [];
    this._current_manifest = null;
    this._update_started = false;
    this._modules_in_update = [];
    this._new_manifest = null;
    this._total_size = 0;
    this._loaded_sizes = {};
  }

  Loader.prototype.get = function(name) {
    return window.localStorage.getItem(name);
  };

  Loader.prototype.set = function(name, value) {
    return window.localStorage.setItem(name, value);
  };

  Loader.prototype.log = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return console.log.apply(console, args);
  };

  Loader.prototype.onUpdateFound = function(event) {
    this.log("onUpdateFound", arguments);
    return this.startUpdate();
  };

  Loader.prototype.onUpToDate = function() {
    return this.log("onUpToDate", arguments);
  };

  Loader.prototype.onUpdateFailed = function() {
    return this.log("onUpdateFailed", arguments);
  };

  Loader.prototype.onUpdateCompletted = function(event) {
    this.log("onUpdateCompletted", arguments);
    return window.location.reload();
  };

  Loader.prototype.onModuleBeginDownload = function() {
    return this.log("onModuleBeginDownload", arguments);
  };

  Loader.prototype.onModuleDownloaded = function() {
    return this.log("onModuleDownloaded", arguments);
  };

  Loader.prototype.onModuleDownloadFailed = function() {
    return this.log("onModuleDownloadFailed", arguments);
  };

  Loader.prototype.onModuleDownloadProgress = function() {
    return this.log("onModuleDownloadProgress", arguments);
  };

  Loader.prototype.onTotalDownloadProgress = function() {
    return this.log("onTotalDownloadProgress", arguments);
  };

  Loader.prototype.onApplicationReady = function() {
    return this.log("onApplicationReady", arguments);
  };

  Loader.prototype.onEvaluationError = function() {
    return this.log("onEvaluationError", arguments);
  };

  Loader.prototype.start = function() {
    var alias, dep, deps, error, evaluator, module, module_source, _i, _len, _ref, _ref1;
    this._current_manifest = this.get("spa::manifest");
    if (this._current_manifest != null) {
      this._modules_running = JSON.parse(this._current_manifest);
      _ref = this._modules_running;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        module = _ref[_i];
        module_source = this.get("spa:" + module.md5 + ":" + module.url);
        if (module_source == null) {
          this.onEvaluationError(new NoSourceError(module.md5, module.url));
        }
        module.source = module_source;
        deps = {};
        _ref1 = module.deps;
        for (alias in _ref1) {
          dep = _ref1[alias];
          deps[alias] = this._all_modules[dep];
        }
        deps["loader"] = this;
        evaluator = new CJSEvaluator({
          id: module.id,
          source: module.source,
          dependencies: deps
        });
        try {
          this._all_modules[module.id] = evaluator.run();
        } catch (_error) {
          error = _error;
          this.onEvaluationError(error);
        }
      }
      this.onApplicationReady();
    } else {
      this.checkUpdate();
    }
  };

  Loader.prototype.checkUpdate = function() {
    var manifest_request;
    if (this._update_started) {
      return;
    }
    this.log("Checking for update...");
    manifest_request = XHR();
    manifest_request.open("GET", "manifest.json", true);
    manifest_request.overrideMimeType("application/json; charset=utf-8");
    manifest_request.onload = (function(_this) {
      return function(event) {
        _this._new_manifest = event.target.response;
        if (_this._current_manifest != null) {
          if (md5(_this._current_manifest) === md5(_this._new_manifest)) {
            _this.onUpToDate();
            return;
          }
        }
        return _this.onUpdateFound(event);
      };
    })(this);
    manifest_request.onerror = (function(_this) {
      return function(event) {
        return _this.onUpdateFailed(event);
      };
    })(this);
    manifest_request.send();
  };

  Loader.prototype.startUpdate = function() {
    var module, _i, _j, _len, _len1, _ref, _ref1;
    this.log("Starting update...");
    this._update_started = true;
    this._modules_in_update = JSON.parse(this._new_manifest);
    this._total_size = 0;
    _ref = this._modules_in_update;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      module = _ref[_i];
      this._total_size += module.size;
      this._loaded_sizes[module.id] = 0;
    }
    _ref1 = this._modules_in_update;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      module = _ref1[_j];
      this._updateModule(module);
    }
  };

  Loader.prototype._updateModule = function(module) {
    var key, module_source;
    key = "spa:" + module.md5 + ":" + module.url;
    module_source = this.get(key);
    if (module_source != null) {
      module.source = module_source;
      this.onTotalDownloadProgress({
        loaded: this._getLoadedSize(),
        total: this._total_size
      });
      this._checkAllUpdated();
    } else {
      this._downloadModule(module);
    }
  };

  Loader.prototype._getLoadedSize = function() {
    var loaded_size, name, size, _ref;
    loaded_size = 0;
    _ref = this._loaded_sizes;
    for (name in _ref) {
      size = _ref[name];
      loaded_size += size;
    }
    return loaded_size;
  };

  Loader.prototype._downloadModule = function(module) {
    var module_request;
    this.onModuleBeginDownload(module);
    module_request = XHR();
    module_request.open("GET", module.url, true);
    module_request.onload = (function(_this) {
      return function(event) {
        var key, module_source;
        module_source = event.target.response;
        if (md5(module_source) !== module.md5) {
          _this.onModuleDownloadFailed(module, event);
        }
        key = "spa:" + module.md5 + ":" + module.url;
        module.source = module_source;
        _this.set(key, module_source);
        _this._loaded_sizes[module.id] = module.size;
        _this.onModuleDownloaded(event);
        _this.onTotalDownloadProgress({
          loaded: _this._getLoadedSize(),
          total: _this._total_size
        });
        return _this._checkAllUpdated();
      };
    })(this);
    module_request.onprogress = (function(_this) {
      return function(event) {
        _this._loaded_sizes[module.id] = event.loaded;
        _this.onModuleDownloadProgress({
          loaded: event.loaded,
          total: module.size
        });
        return _this.onTotalDownloadProgress({
          loaded: _this._getLoadedSize(),
          total: _this._total_size
        });
      };
    })(this);
    module_request.onerror = (function(_this) {
      return function(event) {
        return _this.oModuleDownloadFailed(module, event);
      };
    })(this);
    module_request.onabort = (function(_this) {
      return function(event) {
        return _this.oModuleDownloadFailed(module, event);
      };
    })(this);
    module_request.send();
  };

  Loader.prototype._checkAllUpdated = function() {
    var module, _i, _len, _ref;
    _ref = this._modules_in_update;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      module = _ref[_i];
      if (module.source == null) {
        return;
      }
    }
    this.set("spa::manifest", this._new_manifest);
    this._current_manifest = this._new_manifest;
    this._new_manifest = null;
    this._update_started = false;
    this._modules_in_update = [];
    this.onUpdateCompletted();
  };

  return Loader;

})();

window.onload = function() {
  var loader;
  loader = new Loader();
  loader.start();
  return true;
};
